"""
salarium_options.py — Listes prédéfinies des options Salarium.
"""

BRANCHES = [
    "08. Autres industries extractives",
    "09. Services de soutien aux industries extractives",
    "10. Industries alimentaires",
    "11. Fabrication de boissons",
    "12. Fabrication de produits à base de tabac",
    "13. Fabrication de textiles",
    "14. Industrie de l'habillement",
    "15. Industrie du cuir et de la chaussure",
    "16. Travail du bois et fabrication d'articles en bois et en liège, à l'exception des meubles; fabrication d'articles en vannerie et sparterie",
    "17. Industrie du papier et du carton",
    "18. Imprimerie et reproduction d'enregistrements",
    "19. Cokéfaction et raffinage",
    "20. Industrie chimique",
    "21. Industrie pharmaceutique",
    "22. Fabrication de produits en caoutchouc et en plastique",
    "23. Fabrication d'autres produits minéraux non métalliques",
    "24. Métallurgie",
    "25. Fabrication de produits métalliques, à l'exception des machines et des équipements",
    "26. Fabrication de produits informatiques, électroniques et optiques",
    "27. Fabrication d'équipements électriques",
    "28. Fabrication de machines et équipements n.c.a.",
    "29. Industrie automobile",
    "30. Fabrication d'autres matériels de transport",
    "31. Fabrication de meubles",
    "32. Autres industries manufacturières",
    "33. Réparation et installation de machines et d'équipements",
    "35. Production et distribution d'électricité, de gaz, de vapeur et d'air conditionné",
    "36. Captage, traitement et distribution d'eau",
    "37. Collecte et traitement des eaux usées",
    "38. Collecte, traitement et élimination des déchets; récupération",
    "39. Dépollution et autres services de gestion des déchets",
    "41. Construction de bâtiments",
    "42. Génie civil",
    "43. Travaux de construction spécialisés",
    "45. Commerce et réparation d'automobiles et de motocycles",
    "46. Commerce de gros, à l'exception des automobiles et des motocycles",
    "47. Commerce de détail, à l'exception des automobiles et des motocycles",
    "49. Transports terrestres et transport par conduites",
    "50. Transports par eau",
    "51. Transports aériens",
    "52. Entreposage et services auxiliaires des transports",
    "53. Activités de poste et de courrier",
    "55. Hébergement",
    "56. Restauration",
    "58. Édition",
    "59. Production de films cinématographiques, de vidéo et de programmes de télévision; enregistrement sonore et édition musicale",
    "60. Programmation et diffusion",
    "61. Télécommunications",
    "62. Programmation, conseil et autres activités informatiques",
    "63. Services d'information",
    "64. Activités des services financiers, hors assurance et caisses de retraite",
    "65. Assurance",
    "66. Activités auxiliaires de services financiers et d'assurance",
    "68. Activités immobilières",
    "69. Activités juridiques et comptables",
    "70. Activités des sièges sociaux; conseil de gestion",
    "71. Activités d'architecture et d'ingénierie; activités de contrôle et analyses techniques",
    "72. Recherche-développement scientifique",
    "73. Publicité et études de marché",
    "74. Autres activités spécialisées, scientifiques et techniques",
    "75. Activités vétérinaires",
    "77. Activités de location et location-bail",
    "78. Activités liées à l'emploi",
    "79. Activités des agences de voyage, voyagistes, services de réservation et activités connexes",
    "80. Enquêtes et sécurité",
    "81. Services relatifs aux bâtiments et aménagement paysager",
    "82. Activités administratives et autres activités de soutien aux entreprises",
    "85. Enseignement",
    "86. Activités pour la santé humaine",
    "87. Hébergement médico-social et social",
    "88. Action sociale sans hébergement",
    "90. Activités créatives, artistiques et de spectacle",
    "91. Bibliothèques, archives, musées et autres activités culturelles",
    "92. Organisation de jeux de hasard et d'argent",
    "93. Activités sportives, récréatives et de loisirs",
    "94. Activités des organisations associatives",
    "95. Réparation d'ordinateurs et de biens personnels et domestiques",
    "96. Autres services personnels",
]

REGIONS = [
    "Région lémanique (VD, VS, GE)",
    "Espace Mittelland (BE, FR, SO, NE, JU)",
    "Suisse du Nord-Ouest (BS, BL, AG)",
    "Zurich (ZH)",
    "Suisse orientale (GL, SH, AR, AI, SG, GR, TG)",
    "Suisse centrale (LU, UR, SZ, OW, NW, ZG)",
    "Tessin (TI)",
]

PROFESSIONS = [
    "11-14. Directeurs, cadres de direction et gérants",
    "21. Spécialistes des sciences techniques",
    "22. Spécialistes de la santé",
    "23. Spécialistes de l'enseignement",
    "24. Spécialistes en administration d'entreprises",
    "25. Spécialistes des technologies de l'information et de la communication",
    "26. Spécialistes de la justice, des sciences sociales et de la culture",
    "31. Professions intermédiaires des sciences et techniques",
    "32. Professions intermédiaires de la santé",
    "33. Professions intermédiaires, finance et administration",
    "34. Professions intermédiaires des services juridiques, des services sociaux et assimilés",
    "35. Techniciens de l'information et de la communication",
    "41. Employés de bureau",
    "42. Employés de type administratif avec contact client",
    "43. Employés des services comptables et d'approvisionnement",
    "44. Autres employés de type administratif",
    "51. Personnel des services directs aux particuliers",
    "52. Commerçants et vendeurs",
    "53. Auxiliaires des soins et de l'assistance",
    "54. Personnel des services de protection et de sécurité",
    "61. Agriculteurs et ouvriers qualifiés de l'agriculture commerciale",
    "62. Professions commerciales qualifiées de la sylviculture, de la pêche et de la chasse",
    "71. Métiers qualifiés du bâtiment et assimilés, sauf électriciens",
    "72. Métiers qualifiés de la métallurgie, la construction mécanique, la polymécanique, la mécanique de production et assimilés",
    "73. Métiers qualifiés de l'artisanat et de l'imprimerie",
    "74. Métiers de l'électricité et de l'électrotechnique",
    "75. Métiers de l'alimentation, du travail sur bois, de l'habillement et autres métiers qualifiés de l'industrie et de l'artisanat",
    "81. Conducteurs de machines et d'installations fixes",
    "82. Ouvriers de l'assemblage",
    "83. Conducteurs de véhicules et d'engins lourds de levage et de manoeuvre",
    "91. Aides de ménage et de nettoyage",
    "92. Manoeuvres de l'agriculture, de la pêche et de la sylviculture",
    "93. Manoeuvres des mines, du bâtiment et des travaux publics, des industries manufacturières et des transports",
    "94. Assistants de fabrication de l'alimentation",
    "96. Éboueurs et autres travailleurs non qualifiés",
]

POSITIONS = [
    "1-2. Cadre supérieur et moyen",
    "3-4. Cadre inférieur",
    "5. Sans fonction de cadre",
]

FORMATIONS = [
    "Haute école universitaire (UNI, EPF)",
    "Haute école spécialisée (HES), haute école pédagogique (HEP)",
    "Formation professionnelle supérieure",
    "Brevet d'enseignement",
    "Maturité",
    "Apprentissage complet (CFC)",
    "Formation professionnelle acquise en entreprise",
    "Sans formation professionnelle complète",
]

SEXES = ["Homme", "Femme"]

NATIONALITES = [
    "Suisse/Suissesse",
    "Permis de courte durée (Cat. L)",
    "Permis de séjour (Cat. B)",
    "Permis d'établissement (Cat. C)",
    "Frontalier/Frontalière (Cat. G)",
]

TAILLES_ENTREPRISE = [
    "Moins de 20 employés",
    "20 - 49 employés",
    "50 employés et plus",
]

OUI_NON = ["Non", "Oui"]

TYPES_CONTRAT = ["Salaire mensuel", "Salaire horaire"]
